/**
 * \file binarizeParametersControlWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "binarizeParametersControlWidget.h"
#include "ui_binarizeParametersControlWidget.h"
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"


BinarizeParametersControlWidget::BinarizeParametersControlWidget(QWidget *parent, bool _autoInit, QString _rootPath)
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::BinarizeParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);

    QObject::connect(mUi->thresholdSpinBox, SIGNAL(valueChanged(int)), this, SIGNAL(paramsChanged()));
}

BinarizeParametersControlWidget::~BinarizeParametersControlWidget()
{

    delete mUi;
}

void BinarizeParametersControlWidget::loadParamWidget(WidgetLoader &loader)
{
    BinarizeParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}

void BinarizeParametersControlWidget::saveParamWidget(WidgetSaver  &saver)
{
    BinarizeParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}


BinarizeParameters *BinarizeParametersControlWidget::createParameters() const
{

    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/


    BinarizeParameters *result = new BinarizeParameters(
          mUi->thresholdSpinBox->value()
    );
    return result;
}

void BinarizeParametersControlWidget::setParameters(const BinarizeParameters &input)
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->thresholdSpinBox->setValue(input.threshold());
    blockSignals(wasBlocked);
    emit paramsChanged();
}

void BinarizeParametersControlWidget::setParametersVirtual(void *input)
{
    // Modify widget parameters from outside
    BinarizeParameters *inputCasted = static_cast<BinarizeParameters *>(input);
    setParameters(*inputCasted);
}
