##################################################################
#  This QMAKE PRI File was autogenerated at Сб. марта 28 23:26:51 MSK 2015
##################################################################
SOURCES+= $${UTILSDIR}/filters/ui/bitSelectorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/bitSelectorParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/bitSelectorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/gainOffsetParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/gainOffsetParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/gainOffsetParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/sobelParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/sobelParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/sobelParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/cannyParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/cannyParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/cannyParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/openCVFilterParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/openCVFilterParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/openCVFilterParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/backgroundFilterParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/backgroundFilterParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/backgroundFilterParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/binarizeParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/binarizeParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/binarizeParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/thickeningParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/thickeningParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/thickeningParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/maskingParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/maskingParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/maskingParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/outputFilterParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/outputFilterParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/outputFilterParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/inputFilterParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/inputFilterParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/inputFilterParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/filters/ui/operationParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/filters/ui/operationParametersControlWidget.h
FORMS += $${UTILSDIR}/filters/ui/operationParametersControlWidget.ui

