/**
 * \file maskingParametersControlWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "maskingParametersControlWidget.h"
#include "ui_maskingParametersControlWidget.h"
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"


MaskingParametersControlWidget::MaskingParametersControlWidget(QWidget *parent, bool _autoInit, QString _rootPath)
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::MaskingParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);

    QObject::connect(mUi->invertCheckBox, SIGNAL(stateChanged(int)), this, SIGNAL(paramsChanged()));
}

MaskingParametersControlWidget::~MaskingParametersControlWidget()
{

    delete mUi;
}

void MaskingParametersControlWidget::loadParamWidget(WidgetLoader &loader)
{
    MaskingParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}

void MaskingParametersControlWidget::saveParamWidget(WidgetSaver  &saver)
{
    MaskingParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}


MaskingParameters *MaskingParametersControlWidget::createParameters() const
{

    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/


    MaskingParameters *result = new MaskingParameters(
          mUi->invertCheckBox->isChecked()
    );
    return result;
}

void MaskingParametersControlWidget::setParameters(const MaskingParameters &input)
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->invertCheckBox->setChecked(input.invert());
    blockSignals(wasBlocked);
    emit paramsChanged();
}

void MaskingParametersControlWidget::setParametersVirtual(void *input)
{
    // Modify widget parameters from outside
    MaskingParameters *inputCasted = static_cast<MaskingParameters *>(input);
    setParameters(*inputCasted);
}
