/**
 * \file operationParametersControlWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "operationParametersControlWidget.h"
#include "ui_operationParametersControlWidget.h"
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"


OperationParametersControlWidget::OperationParametersControlWidget(QWidget *parent, bool _autoInit, QString _rootPath)
    : FilterParametersControlWidgetBase(parent)
    , mUi(new Ui::OperationParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);

    QObject::connect(mUi->operationComboBox, SIGNAL(currentIndexChanged(int)), this, SIGNAL(paramsChanged()));
}

OperationParametersControlWidget::~OperationParametersControlWidget()
{

    delete mUi;
}

void OperationParametersControlWidget::loadParamWidget(WidgetLoader &loader)
{
    OperationParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}

void OperationParametersControlWidget::saveParamWidget(WidgetSaver  &saver)
{
    OperationParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}

 /* Composite fields are NOT supported so far */
void OperationParametersControlWidget::getParameters(OperationParameters& params) const
{

    params.setOperation        (static_cast<Operation::Operation>(mUi->operationComboBox->currentIndex()));

}

OperationParameters *OperationParametersControlWidget::createParameters() const
{

    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/


    OperationParameters *result = new OperationParameters(
          static_cast<Operation::Operation>(mUi->operationComboBox->currentIndex())
    );
    return result;
}

void OperationParametersControlWidget::setParameters(const OperationParameters &input)
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->operationComboBox->setCurrentIndex(input.operation());
    blockSignals(wasBlocked);
    emit paramsChanged();
}

void OperationParametersControlWidget::setParametersVirtual(void *input)
{
    // Modify widget parameters from outside
    OperationParameters *inputCasted = static_cast<OperationParameters *>(input);
    setParameters(*inputCasted);
}
