#ifndef PARAMETERS_MAPPER_EGOMOTION_H_
#define PARAMETERS_MAPPER_EGOMOTION_H_
/**
 * \file parametersMapperEgomotion.h
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include <iostream>
#include <QtCore/QSharedPointer>

#include "core/reflection/reflection.h"
#include "core/reflection/defaultSetter.h"

#include "baseParametersControlWidget.h"
#include "egomotionParametersControlWidget.h"
#include "presentationParametersControlWidget.h"

class ParametersMapperEgomotion : public QObject
{
    Q_OBJECT
public:
    ParametersMapperEgomotion();

    void setBaseParametersControlWidget(BaseParametersControlWidget *widget);
    void setEgomotionParametersControlWidget(EgomotionParametersControlWidget *widget);
    void setPresentationParametersControlWidget(PresentationParametersControlWidget *widget);

public slots:
    void paramsChanged();

signals:
    void baseParametersParamsChanged(QSharedPointer<BaseParameters> params);
    void egomotionParametersParamsChanged(QSharedPointer<EgomotionParameters> params);
    void presentationParametersParamsChanged(QSharedPointer<PresentationParameters> params);

private:
    BaseParametersControlWidget *mBaseParametersControlWidget;
    EgomotionParametersControlWidget *mEgomotionParametersControlWidget;
    PresentationParametersControlWidget *mPresentationParametersControlWidget;
};
#endif //PARAMETERS_MAPPER_EGOMOTION_H_
