export enum AttitudeTargetTypemask {
	ATTITUDE_TARGET_TYPEMASK_BODY_ROLL_RATE_IGNORE = 1, // Ignore body roll rate
	ATTITUDE_TARGET_TYPEMASK_BODY_PITCH_RATE_IGNORE = 2, // Ignore body pitch rate
	ATTITUDE_TARGET_TYPEMASK_BODY_YAW_RATE_IGNORE = 4, // Ignore body yaw rate
	ATTITUDE_TARGET_TYPEMASK_THROTTLE_IGNORE = 64, // Ignore throttle
	ATTITUDE_TARGET_TYPEMASK_ATTITUDE_IGNORE = 128, // Ignore attitude
	ATTITUDE_TARGET_TYPEMASK_ENUM_END = 129, // 
}