export enum EscConnectionType {
	ESC_CONNECTION_TYPE_PPM = 0, // Traditional PPM ESC.
	ESC_CONNECTION_TYPE_SERIAL = 1, // Serial Bus connected ESC.
	ESC_CONNECTION_TYPE_ONESHOT = 2, // One Shot PPM ESC.
	ESC_CONNECTION_TYPE_I2C = 3, // I2C ESC.
	ESC_CONNECTION_TYPE_CAN = 4, // CAN-Bus ESC.
	ESC_CONNECTION_TYPE_DSHOT = 5, // DShot ESC.
	ESC_CONNECTION_TYPE_ENUM_END = 6, // 
}