export enum FailureUnit {
	FAILURE_UNIT_SENSOR_GYRO = 0, // 
	FAILURE_UNIT_SENSOR_ACCEL = 1, // 
	FAILURE_UNIT_SENSOR_MAG = 2, // 
	FAILURE_UNIT_SENSOR_BARO = 3, // 
	FAILURE_UNIT_SENSOR_GPS = 4, // 
	FAILURE_UNIT_SENSOR_OPTICAL_FLOW = 5, // 
	FAILURE_UNIT_SENSOR_VIO = 6, // 
	FAILURE_UNIT_SENSOR_DISTANCE_SENSOR = 7, // 
	FAILURE_UNIT_SENSOR_AIRSPEED = 8, // 
	FAILURE_UNIT_SYSTEM_BATTERY = 100, // 
	FAILURE_UNIT_SYSTEM_MOTOR = 101, // 
	FAILURE_UNIT_SYSTEM_SERVO = 102, // 
	FAILURE_UNIT_SYSTEM_AVOIDANCE = 103, // 
	FAILURE_UNIT_SYSTEM_RC_SIGNAL = 104, // 
	FAILURE_UNIT_SYSTEM_MAVLINK_SIGNAL = 105, // 
	FAILURE_UNIT_ENUM_END = 106, // 
}