export enum GimbalManagerFlags {
	GIMBAL_MANAGER_FLAGS_RETRACT = 1, // Based on GIMBAL_DEVICE_FLAGS_RETRACT
	GIMBAL_MANAGER_FLAGS_NEUTRAL = 2, // Based on GIMBAL_DEVICE_FLAGS_NEUTRAL
	GIMBAL_MANAGER_FLAGS_ROLL_LOCK = 4, // Based on GIMBAL_DEVICE_FLAGS_ROLL_LOCK
	GIMBAL_MANAGER_FLAGS_PITCH_LOCK = 8, // Based on GIMBAL_DEVICE_FLAGS_PITCH_LOCK
	GIMBAL_MANAGER_FLAGS_YAW_LOCK = 16, // Based on GIMBAL_DEVICE_FLAGS_YAW_LOCK
	GIMBAL_MANAGER_FLAGS_ENUM_END = 17, // 
}