/**
 * \file copterWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "copterWidget.h"
#include "ui_copterWidget.h"
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"

CopterWidget::CopterWidget(QWidget *parent)
    : QWidget(parent)
    , mUi(new Ui::CopterWidget)
{
    mUi->setupUi(this);

    Copter *params = createParameters();
    SettingsGetter visitor("cvs.conf");
    params->accept<SettingsGetter>(visitor);
    setParameters(*params);
    delete params;

    QObject::connect(mUi->pathEdit, SIGNAL(textEdited(QString)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fileTemplateEdit, SIGNAL(textEdited(QString)), this, SIGNAL(paramsChanged()));
}

CopterWidget::~CopterWidget()
{
    Copter *params = createParameters();
    SettingsSetter visitor("cvs.conf");
    params->accept<SettingsSetter>(visitor);
    setParameters(*params);
    delete params;

    delete mUi;
}

Copter *CopterWidget::createParameters() const
{
    return new Copter(
          mUi->pathEdit->text().toStdString()
        , mUi->fileTemplateEdit->text().toStdString()
    );
}

void CopterWidget::setParameters(const Copter &input)
{
    mUi->pathEdit->setText(input.path().c_str());
    mUi->fileTemplateEdit->setText(input.fileTemplate().c_str());
}
