/**
 * \file recorderWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "recorderWidget.h"
#include "ui_recorderWidget.h"
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"

RecorderWidget::RecorderWidget(QWidget *parent)
    : QWidget(parent)
    , mUi(new Ui::RecorderWidget)
{
    mUi->setupUi(this);

    Recorder *params = createParameters();
    SettingsGetter visitor("cvs.conf");
    params->accept<SettingsGetter>(visitor);
    setParameters(*params);
    delete params;

    QObject::connect(mUi->pathEdit, SIGNAL(textEdited(QString)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->fileTemplateEdit, SIGNAL(textEdited(QString)), this, SIGNAL(paramsChanged()));
}

RecorderWidget::~RecorderWidget()
{
    Recorder *params = createParameters();
    SettingsSetter visitor("cvs.conf");
    params->accept<SettingsSetter>(visitor);
    setParameters(*params);
    delete params;

    delete mUi;
}

Recorder *RecorderWidget::createParameters() const
{
    return new Recorder(
          mUi->pathEdit->text().toStdString()
        , mUi->fileTemplateEdit->text().toStdString()
    );
}

void RecorderWidget::setParameters(const Recorder &input)
{
    mUi->pathEdit->setText(input.path().c_str());
    mUi->fileTemplateEdit->setText(input.fileTemplate().c_str());
}
