/**
 * \file recorder.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 * Generated from recorder.xml
 */

#include <vector>
#include <stddef.h>
#include "recorder.h"

/**
 *  Looks extremely unsafe because it depends on the order of static initialization.
 *  Should check standard if this is ok
 *
 *  Also it's not clear why removing "= Reflection()" breaks the code;
 **/

namespace corecvs {
#if 0
template<>
Reflection BaseReflection<Recorder>::reflection = Reflection();
template<>
int BaseReflection<Recorder>::dummy = Recorder::staticInit();
#endif
} // namespace corecvs 

SUPPRESS_OFFSET_WARNING_BEGIN


using namespace corecvs;

int Recorder::staticInit(corecvs::Reflection *toFill)
{
    if (toFill == NULL || toFill->objectSize != 0) {
        SYNC_PRINT(("staticInit(): Contract Violation in <Recorder>\n"));
         return -1;
    }

    toFill->name = ReflectionNaming(
        "Recorder",
        "Recorder parameters",
        ""
    );

     toFill->objectSize = sizeof(Recorder);
     

    StringField* field0 = new StringField
        (
          Recorder::PATH_ID,
          offsetof(Recorder, mPath),
          "",
          "path",
          "path",
          "path"
        );
    toFill->fields.push_back(field0);
    /*  */ 
    StringField* field1 = new StringField
        (
          Recorder::FILETEMPLATE_ID,
          offsetof(Recorder, mFileTemplate),
          "sequence_%04d_c%d.pgm",
          "fileTemplate",
          "fileTemplate",
          "fileTemplate"
        );
    toFill->fields.push_back(field1);
    /*  */ 
    ReflectionDirectory &directory = *ReflectionDirectoryHolder::getReflectionDirectory();
    directory[std::string("Recorder")]= toFill;
   return 0;
}
int Recorder::relinkCompositeFields()
{
   return 0;
}

SUPPRESS_OFFSET_WARNING_END


