/**
 * \file recorder.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include <vector>
#include <stddef.h>
#include "recorder.h"

/**
 *  Looks extremely unsafe because it depends on the order of static initialization.
 *  Should check standard if this is ok
 *
 *  Also it's not clear why removing "= Reflection()" breaks the code;
 **/

namespace corecvs {
template<>
Reflection BaseReflection<Recorder>::reflection = Reflection();
template<>
int BaseReflection<Recorder>::dummy = Recorder::staticInit();
} // namespace corecvs 

SUPPRESS_OFFSET_WARNING_BEGIN

int Recorder::staticInit()
{

    ReflectionNaming &nameing = naming();
    nameing = ReflectionNaming(
        "Recorder",
        "Recorder parameters",
        ""
    );
     

    fields().push_back(
        new StringField
        (
          Recorder::PATH_ID,
          offsetof(Recorder, mPath),
          "",
          "path",
          "path",
          "path"
        )
    );
    fields().push_back(
        new StringField
        (
          Recorder::FILETEMPLATE_ID,
          offsetof(Recorder, mFileTemplate),
          "sequence_%04d_c%d.pgm",
          "fileTemplate",
          "fileTemplate",
          "fileTemplate"ay
        )
    );
   return 0;
}

SUPPRESS_OFFSET_WARNING_END


