#ifndef MATCHING_METHOD_TYPE_H_
#define MATCHING_METHOD_TYPE_H_
/**
 * \file matchingMethodType.h
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

/**
 * Helper namespace to hide MatchingMethodType enum from global context.
 */

namespace MatchingMethodType {

/** 
 * \brief Matching Method Type 
 * Matching Method Type 
 */
enum MatchingMethodType {
    /** 
     * \brief SurfCV 
     * SurfCV 
     */
    SURFCV = 0,
    /** 
     * \brief viTech 
     * viTech 
     */
    VITECH = 1,
    /** 
     * \brief Last virtual option to run cycles to
     */
    MATCHING_METHOD_TYPE_LAST
};

} //namespace MatchingMethodType

#endif  //MATCHING_METHOD_TYPE_H_
