#ifndef PARAMETERS_MAPPER_SCANNER_H_
#define PARAMETERS_MAPPER_SCANNER_H_
/**
 * \file parametersMapperScanner.h
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include <iostream>
#include <QtCore/QSharedPointer>

#include "core/reflection/reflection.h"
#include "core/reflection/defaultSetter.h"

#include "baseParametersControlWidget.h"
#include "scannerParametersControlWidget.h"
#include "presentationParametersControlWidget.h"

class ParametersMapperScanner : public QObject
{
    Q_OBJECT
public:
    ParametersMapperScanner();

    void setBaseParametersControlWidget(BaseParametersControlWidget *widget);
    void setScannerParametersControlWidget(ScannerParametersControlWidget *widget);
    void setPresentationParametersControlWidget(PresentationParametersControlWidget *widget);

public slots:
    void paramsChanged();

signals:
    void baseParametersParamsChanged(QSharedPointer<BaseParameters> params);
    void scannerParametersParamsChanged(QSharedPointer<ScannerParameters> params);
    void presentationParametersParamsChanged(QSharedPointer<PresentationParameters> params);

private:
    BaseParametersControlWidget *mBaseParametersControlWidget;
    ScannerParametersControlWidget *mScannerParametersControlWidget;
    PresentationParametersControlWidget *mPresentationParametersControlWidget;
};
#endif //PARAMETERS_MAPPER_SCANNER_H_
