/**
 * \file axisAlignedBoxParametersControlWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "axisAlignedBoxParametersControlWidget.h"
#include "ui_axisAlignedBoxParametersControlWidget.h"
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"


AxisAlignedBoxParametersControlWidget::AxisAlignedBoxParametersControlWidget(QWidget *parent, bool _autoInit, QString _rootPath)
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::AxisAlignedBoxParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);

    QObject::connect(mUi->xSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->ySpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->zSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->widthSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->heightSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->depthSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
}

AxisAlignedBoxParametersControlWidget::~AxisAlignedBoxParametersControlWidget()
{

    delete mUi;
}

void AxisAlignedBoxParametersControlWidget::loadParamWidget(WidgetLoader &loader)
{
    AxisAlignedBoxParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}

void AxisAlignedBoxParametersControlWidget::saveParamWidget(WidgetSaver  &saver)
{
    AxisAlignedBoxParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}


AxisAlignedBoxParameters *AxisAlignedBoxParametersControlWidget::createParameters() const
{

    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/


    AxisAlignedBoxParameters *result = new AxisAlignedBoxParameters(
          mUi->xSpinBox->value()
        , mUi->ySpinBox->value()
        , mUi->zSpinBox->value()
        , mUi->widthSpinBox->value()
        , mUi->heightSpinBox->value()
        , mUi->depthSpinBox->value()
    );
    return result;
}

void AxisAlignedBoxParametersControlWidget::setParameters(const AxisAlignedBoxParameters &input)
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->xSpinBox->setValue(input.x());
    mUi->ySpinBox->setValue(input.y());
    mUi->zSpinBox->setValue(input.z());
    mUi->widthSpinBox->setValue(input.width());
    mUi->heightSpinBox->setValue(input.height());
    mUi->depthSpinBox->setValue(input.depth());
    blockSignals(wasBlocked);
    emit paramsChanged();
}

void AxisAlignedBoxParametersControlWidget::setParametersVirtual(void *input)
{
    // Modify widget parameters from outside
    AxisAlignedBoxParameters *inputCasted = static_cast<AxisAlignedBoxParameters *>(input);
    setParameters(*inputCasted);
}
