##################################################################
#  This QMAKE PRI File was autogenerated Сб. марта 28 23:26:51 MSK 2015
##################################################################
SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.ui

