##################################################################
#  This QMAKE PRI File was autogenerated Fri Oct  4 15:40:31 MSK 2013
##################################################################
SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.ui

