##################################################################
#  This QMAKE PRI File was autogenerated Пт. дек. 18 19:41:36 MSK 2015
##################################################################
SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/rgbColorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/axisAlignedBoxParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/headSearchParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/makePreciseParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/debayerParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/checkerboardDetectionParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/lineDistortionEstimatorParametersControlWidget.ui

SOURCES+= $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.cpp
HEADERS+= $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.h
FORMS += $${UTILSDIR}/corestructs/coreWidgets/distortionApplicationParametersControlWidget.ui

