/**
 * \file lensDistortionModelParametersControlWidget.cpp
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "lensDistortionModelParametersControlWidget.h"
#include "ui_lensDistortionModelParametersControlWidget.h"
#include "qSettingsGetter.h"
#include "qSettingsSetter.h"


LensDistortionModelParametersControlWidget::LensDistortionModelParametersControlWidget(QWidget *parent, bool _autoInit, QString _rootPath)
    : ParametersControlWidgetBase(parent)
    , mUi(new Ui::LensDistortionModelParametersControlWidget)
    , autoInit(_autoInit)
    , rootPath(_rootPath)
{
    mUi->setupUi(this);

    QObject::connect(mUi->principalXSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->principalYSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->tangentialXSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->tangentialYSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->koeff, SIGNAL(), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->aspectSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->scaleSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
    QObject::connect(mUi->normalizingFocalSpinBox, SIGNAL(valueChanged(double)), this, SIGNAL(paramsChanged()));
}

LensDistortionModelParametersControlWidget::~LensDistortionModelParametersControlWidget()
{

    delete mUi;
}

void LensDistortionModelParametersControlWidget::loadParamWidget(WidgetLoader &loader)
{
    LensDistortionModelParameters *params = createParameters();
    loader.loadParameters(*params, rootPath);
    setParameters(*params);
    delete params;
}

void LensDistortionModelParametersControlWidget::saveParamWidget(WidgetSaver  &saver)
{
    LensDistortionModelParameters *params = createParameters();
    saver.saveParameters(*params, rootPath);
    delete params;
}

 /* Composite fields are NOT supported so far */
void LensDistortionModelParametersControlWidget::getParameters(LensDistortionModelParameters& params) const
{

    params.setPrincipalX       (mUi->principalXSpinBox->value());
    params.setPrincipalY       (mUi->principalYSpinBox->value());
    params.setTangentialX      (mUi->tangentialXSpinBox->value());
    params.setTangentialY      (mUi->tangentialYSpinBox->value());
    params.setKoeff            (mUi->koeff->);
    params.setAspect           (mUi->aspectSpinBox->value());
    params.setScale            (mUi->scaleSpinBox->value());
    params.setNormalizingFocal (mUi->normalizingFocalSpinBox->value());

}

LensDistortionModelParameters *LensDistortionModelParametersControlWidget::createParameters() const
{

    /**
     * We should think of returning parameters by value or saving them in a preallocated place
     **/


    LensDistortionModelParameters *result = new LensDistortionModelParameters(
          mUi->principalXSpinBox->value()
        , mUi->principalYSpinBox->value()
        , mUi->tangentialXSpinBox->value()
        , mUi->tangentialYSpinBox->value()
        , mUi->koeff->
        , mUi->aspectSpinBox->value()
        , mUi->scaleSpinBox->value()
        , mUi->normalizingFocalSpinBox->value()
    );
    return result;
}

void LensDistortionModelParametersControlWidget::setParameters(const LensDistortionModelParameters &input)
{
    // Block signals to send them all at once
    bool wasBlocked = blockSignals(true);
    mUi->principalXSpinBox->setValue(input.principalX());
    mUi->principalYSpinBox->setValue(input.principalY());
    mUi->tangentialXSpinBox->setValue(input.tangentialX());
    mUi->tangentialYSpinBox->setValue(input.tangentialY());
    mUi->koeff->(input.koeff());
    mUi->aspectSpinBox->setValue(input.aspect());
    mUi->scaleSpinBox->setValue(input.scale());
    mUi->normalizingFocalSpinBox->setValue(input.normalizingFocal());
    blockSignals(wasBlocked);
    emit paramsChanged();
}

void LensDistortionModelParametersControlWidget::setParametersVirtual(void *input)
{
    // Modify widget parameters from outside
    LensDistortionModelParameters *inputCasted = static_cast<LensDistortionModelParameters *>(input);
    setParameters(*inputCasted);
}
