SET(SOAPYSDR_INCLUDE_SEARCH_PATHS
    /usr/include
    /usr/local/include
    $ENV{SOAPYSDR_HOME}
    $ENV{SOAPYSDR_HOME}/include
)

SET(SOAPYSDR_LIB_SEARCH_PATHS
    /lib/
    /lib64/
    /usr/lib
    /usr/lib64
    /usr/local/lib
    /usr/local/lib64
    $ENV{SOAPYSDR_HOME}
    $ENV{SOAPYSDR_HOME}/lib
)

FIND_PATH(SOAPYSDR_INCLUDE_DIR NAMES SoapySDR/Version.h PATHS ${SOAPYSDR_INCLUDE_SEARCH_PATHS})
FIND_LIBRARY(SOAPYSDR_LIB NAMES SoapySDR PATHS ${SOAPYSDR_LIB_SEARCH_PATHS})

SET(SOAPYSDR_FOUND ON)

#    Check include files
IF(NOT SOAPYSDR_INCLUDE_DIR)
  SET(SOAPYSDR_FOUND OFF)
  MESSAGE(STATUS "Could not find SOAPYSDR include. Turning SOAPYSDR_FOUND off")
ENDIF()

#    Check libraries
IF(NOT SOAPYSDR_LIB)
  SET(SOAPYSDR_FOUND OFF)
  MESSAGE(STATUS "Could not find SOAPYSDR lib. Turning SOAPYSDR_FOUND off")
ENDIF()

IF (SOAPYSDR_FOUND)
IF (NOT SOAPYSDR_FIND_QUIETLY)
  MESSAGE(STATUS "Found SOAPYSDR libraries: ${SOAPYSDR_LIB}")
  MESSAGE(STATUS "Found SOAPYSDR include: ${SOAPYSDR_INCLUDE_DIR}")
ENDIF (NOT SOAPYSDR_FIND_QUIETLY)
ELSE (SOAPYSDR_FOUND)
IF (SOAPYSDR_FIND_REQUIRED)
  MESSAGE(FATAL_ERROR "Could not find SOAPYSDR")
ENDIF (SOAPYSDR_FIND_REQUIRED)
ENDIF (SOAPYSDR_FOUND)

MARK_AS_ADVANCED(
  SOAPYSDR_INCLUDE_DIR
  SOAPYSDR_LIB
  SOAPYSDR
)
