/**
 * \file parametersMapperRecorder.cpp
 * \attention This file is automatically generated and should not be in general modifed manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

#include "parametersMapperRecorder.h"

ParametersMapperRecorder::ParametersMapperRecorder() :
    mBaseParametersControlWidget(NULL)
  , mRecorderControlWidget(NULL)
  , mPresentationParametersControlWidget(NULL)
{
    qRegisterMetaType<QSharedPointer<BaseParameters> >("QSharedPointer<BaseParameters>");
    qRegisterMetaType<QSharedPointer<Recorder> >("QSharedPointer<Recorder>");
    qRegisterMetaType<QSharedPointer<PresentationParameters> >("QSharedPointer<PresentationParameters>");
}

void ParametersMapperRecorder::setBaseParametersControlWidget(BaseParametersControlWidget *widget)
{
    mBaseParametersControlWidget = widget;
    QObject::connect(mBaseParametersControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}

void ParametersMapperRecorder::setRecorderControlWidget(RecorderControlWidget *widget)
{
    mRecorderControlWidget = widget;
    QObject::connect(mRecorderControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}

void ParametersMapperRecorder::setPresentationParametersControlWidget(PresentationParametersControlWidget *widget)
{
    mPresentationParametersControlWidget = widget;
    QObject::connect(mPresentationParametersControlWidget, SIGNAL(paramsChanged()), this, SLOT(paramsChanged()));
}

void ParametersMapperRecorder::paramsChanged()
{
    if (mBaseParametersControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperRecorder \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit baseParametersParamsChanged(QSharedPointer<BaseParameters>(mBaseParametersControlWidget->createParameters()));


    if (mRecorderControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperRecorder \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit recorderParamsChanged(QSharedPointer<Recorder>(mRecorderControlWidget->createParameters()));


    if (mPresentationParametersControlWidget == NULL)
    {
          std::cout << "One of the fields for ParametersMapperRecorder \n"
               "is still NULL but the mapper is already in use. This will cause crash.\n"
               "You should modify your <HostWidget>::createCalculator() function" << std::endl;
    }
    emit presentationParametersParamsChanged(QSharedPointer<PresentationParameters>(mPresentationParametersControlWidget->createParameters()));


}

