#ifndef OUTPUT_STYLE_H_
#define OUTPUT_STYLE_H_
/**
 * \file outputStyle.h
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

/**
 * Helper namespace to hide OutputStyle enum from global context.
 */

namespace OutputStyle {

/** 
 * \brief Output Style 
 * Output Style 
 */
enum OutputStyle {
    /** 
     * \brief standart output 
     * Standart output 
     */
    STANDART_OUTPUT = 0,
    /** 
     * \brief sidebyside stereo 
     * Side-by-side stereo 
     */
    SIDEBYSIDE_STEREO = 1,
    /** 
     * \brief anaglyph RG 
     * Red-Green Anaglyph 
     */
    ANAGLYPH_RG = 2,
    /** 
     * \brief anaglyph RC 
     * Red-Cyan Anaglyph 
     */
    ANAGLYPH_RC = 3,
    /** 
     * \brief blend 
     * Blend 
     */
    BLEND = 4,
    /** 
     * \brief none 
     * None 
     */
    NONE = 5,
    /** 
     * \brief Last virtual option to run cycles to
     */
    OUTPUT_STYLE_LAST
};

} //namespace OutputStyle

#endif  //OUTPUT_STYLE_H_
