#ifndef ROTATION_PRESETS_H_
#define ROTATION_PRESETS_H_
/**
 * \file rotationPresets.h
 * \attention This file is automatically generated and should not be in general modified manually
 *
 * \date MMM DD, 20YY
 * \author autoGenerator
 */

/**
 * Helper namespace to hide RotationPresets enum from global context.
 */

namespace RotationPresets {

/** 
 * \brief Rotation Presets 
 * Rotation Presets 
 */
enum RotationPresets {
    /** 
     * \brief No rotation 
     * No rotation 
     */
    NO_ROTATION = 0,
    /** 
     * \brief Clockwise 90deg 
     * Clockwise 90deg 
     */
    CLOCKWISE_90DEG = 1,
    /** 
     * \brief Clockwise 180deg 
     * Clockwise 180deg 
     */
    CLOCKWISE_180DEG = 2,
    /** 
     * \brief Clockwise 270deg 
     * Clockwise 270deg 
     */
    CLOCKWISE_270DEG = 3,
    /** 
     * \brief Last virtual option to run cycles to
     */
    ROTATION_PRESETS_LAST
};

} //namespace RotationPresets

#endif  //ROTATION_PRESETS_H_
